databases:
  - name: moshimonotayori_db #Renderで作成したDBアプリ名
    databaseName: moshimonotayori_db #「Info内のConnectionsにあるDatabase」を入れる
    user: moshimonotayori #Renderで作成したRailsのアプリ名
    region: singapore

services:
  - type: web
    name: moshimonotayori #Renderで作成したRailsのアプリ名
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moshimonotayori_db #Renderで作成したDBアプリ名
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

